# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:30
from __future__ import unicode_literals

from django.db import migrations
import kakera_blog.models
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', kakera_blog.models.MarkdownBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()))),
        ),
    ]
