# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_blog', '0002_auto_20161118_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='cover_embed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
