# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:08
from __future__ import unicode_literals

from django.db import migrations
import kakera_blog.models
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_blog', '0006_auto_20161201_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', kakera_blog.models.MarkdownBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('steam_widget', kakera_blog.models.SteamWidgetBlock(help_text='Enter a Steam ID, eg. to embed Harmonia (https://store.steampowered.com/app/421660), enter: 421660.')))),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', kakera_blog.models.MarkdownBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('steam_widget', kakera_blog.models.SteamWidgetBlock(help_text='Enter a Steam ID, eg. to embed Harmonia (https://store.steampowered.com/app/421660), enter: 421660.')))),
        ),
    ]
