# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_blog', '0011_auto_20170224_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
