# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_core', '0005_settings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='facebook_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
