# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_core', '0008_auto_20161204_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='facebook_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
