# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import kakera_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_core', '0010_settings_facebook_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=15, validators=[kakera_core.models.validate_no_at_prefix]),
        ),
    ]
