# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_core', '0011_auto_20161214_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cloudflare_zone_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
