# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_core', '0013_auto_20170204_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kakera_core.CustomImage'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kakera_core.CustomImage'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kakera_core.CustomImage'),
        ),
    ]
