# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_core', '0016_settings_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='color',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
