# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakera_core', '0017_customimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='extra_head',
            field=models.TextField(blank=True),
        ),
    ]
